export const BULK_NOTIFICATION_TARGET_GROUP = {
  ALL_USERS: 'ALL_USERS',
  PATIENTS: 'PATIENTS',
  DOCTORS: 'DOCTORS',
  BY_SPECIALTY: 'BY_SPECIALTY',
  ADVANCED_FILTER: 'ADVANCED_FILTER',
} as const;

export type BulkNotificationTargetGroup =
  (typeof BULK_NOTIFICATION_TARGET_GROUP)[keyof typeof BULK_NOTIFICATION_TARGET_GROUP];

export const BULK_NOTIFICATION_RECIPIENT_SCOPE = {
  PATIENTS: 'PATIENTS',
  DOCTORS: 'DOCTORS',
  ALL_USERS: 'ALL_USERS',
} as const;

export type BulkNotificationRecipientScope =
  (typeof BULK_NOTIFICATION_RECIPIENT_SCOPE)[keyof typeof BULK_NOTIFICATION_RECIPIENT_SCOPE];

export const BULK_NOTIFICATION_TARGET_GROUP_VALUES: BulkNotificationTargetGroup[] = [
  BULK_NOTIFICATION_TARGET_GROUP.ALL_USERS,
  BULK_NOTIFICATION_TARGET_GROUP.PATIENTS,
  BULK_NOTIFICATION_TARGET_GROUP.DOCTORS,
  BULK_NOTIFICATION_TARGET_GROUP.BY_SPECIALTY,
  BULK_NOTIFICATION_TARGET_GROUP.ADVANCED_FILTER,
];

export const BULK_NOTIFICATION_RECIPIENT_SCOPE_VALUES: BulkNotificationRecipientScope[] = [
  BULK_NOTIFICATION_RECIPIENT_SCOPE.PATIENTS,
  BULK_NOTIFICATION_RECIPIENT_SCOPE.DOCTORS,
  BULK_NOTIFICATION_RECIPIENT_SCOPE.ALL_USERS,
];

