export const BULK_NOTIFICATION_TARGET_GROUP = {
  ALL_USERS: 'ALL_USERS',
  PATIENTS: 'PATIENTS',
  DOCTORS: 'DOCTORS',
  BY_SPECIALTY: 'BY_SPECIALTY',
  ADVANCED_FILTER: 'ADVANCED_FILTER',
} as const;

export type BulkNotificationTargetGroup =
  (typeof BULK_NOTIFICATION_TARGET_GROUP)[keyof typeof BULK_NOTIFICATION_TARGET_GROUP];

export const BULK_NOTIFICATION_RECIPIENT_SCOPE = {
  PATIENTS: 'PATIENTS',
  DOCTORS: 'DOCTORS',
  ALL_USERS: 'ALL_USERS',
} as const;

export type BulkNotificationRecipientScope =
  (typeof BULK_NOTIFICATION_RECIPIENT_SCOPE)[keyof typeof BULK_NOTIFICATION_RECIPIENT_SCOPE];

export const BULK_NOTIFICATION_TARGET_GROUP_VALUES: BulkNotificationTargetGroup[] = [
  BULK_NOTIFICATION_TARGET_GROUP.ALL_USERS,
  BULK_NOTIFICATION_TARGET_GROUP.PATIENTS,
  BULK_NOTIFICATION_TARGET_GROUP.DOCTORS,
  BULK_NOTIFICATION_TARGET_GROUP.BY_SPECIALTY,
  BULK_NOTIFICATION_TARGET_GROUP.ADVANCED_FILTER,
];

export const BULK_NOTIFICATION_RECIPIENT_SCOPE_VALUES: BulkNotificationRecipientScope[] = [
  BULK_NOTIFICATION_RECIPIENT_SCOPE.PATIENTS,
  BULK_NOTIFICATION_RECIPIENT_SCOPE.DOCTORS,
  BULK_NOTIFICATION_RECIPIENT_SCOPE.ALL_USERS,
];

export const BULK_NOTIFICATION_QUICK_PRESET = {
  ALL_PATIENTS: 'all_patients',
  ALL_DOCTORS: 'all_doctors',
  ALL_USERS: 'all_users',
  PATIENTS_TODAY: 'patients_today',
  PATIENTS_TOMORROW: 'patients_tomorrow',
} as const;

export type BulkNotificationQuickPreset =
  (typeof BULK_NOTIFICATION_QUICK_PRESET)[keyof typeof BULK_NOTIFICATION_QUICK_PRESET];

export const BULK_NOTIFICATION_QUICK_PRESET_VALUES: BulkNotificationQuickPreset[] = [
  BULK_NOTIFICATION_QUICK_PRESET.ALL_PATIENTS,
  BULK_NOTIFICATION_QUICK_PRESET.ALL_DOCTORS,
  BULK_NOTIFICATION_QUICK_PRESET.ALL_USERS,
  BULK_NOTIFICATION_QUICK_PRESET.PATIENTS_TODAY,
  BULK_NOTIFICATION_QUICK_PRESET.PATIENTS_TOMORROW,
];
