CREATE TABLE "LICH_BSK_NHAP" (
  "LBN_ID" SERIAL NOT NULL,
  "CK_MA" INTEGER NOT NULL,
  "LBN_TU_NGAY" DATE NOT NULL,
  "LBN_DEN_NGAY" DATE NOT NULL,
  "LBN_DU_LIEU" JSONB NOT NULL,
  "LBN_TAO_LUC" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
  "LBN_TAO_BOI" TEXT,
  "LBN_CAP_NHAT_LUC" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
  "LBN_CAP_NHAT_BOI" TEXT,
  CONSTRAINT "LICH_BSK_NHAP_pkey" PRIMARY KEY ("LBN_ID"),
  CONSTRAINT "fk_lbn_ck" FOREIGN KEY ("CK_MA") REFERENCES "CHUYEN_KHOA"("CK_MA") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE INDEX "idx_lbn_ck" ON "LICH_BSK_NHAP"("CK_MA");
CREATE INDEX "idx_lbn_khoang" ON "LICH_BSK_NHAP"("LBN_TU_NGAY", "LBN_DEN_NGAY");
