ALTER TABLE "LICH_BSK"
ADD COLUMN "LBM_ID" INTEGER,
ADD COLUMN "DLT_TUAN_BAT_DAU" DATE,
ADD COLUMN "LBSK_NGUON" TEXT NOT NULL DEFAULT 'legacy_registration',
ADD COLUMN "LBSK_TRANG_THAI" TEXT NOT NULL DEFAULT 'generated',
ADD COLUMN "LBSK_TAO_LUC" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "LBSK_CAP_NHAT_LUC" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "LBSK_XAC_NHAN_LUC" TIMESTAMP(6);

CREATE TABLE "LICH_BSK_MAU" (
  "LBM_ID" SERIAL NOT NULL,
  "BS_MA" INTEGER NOT NULL,
  "CK_MA" INTEGER NOT NULL,
  "P_MA" INTEGER NOT NULL,
  "B_TEN" TEXT NOT NULL,
  "LBM_THU_TRONG_TUAN" INTEGER NOT NULL,
  "LBM_HIEU_LUC_TU" DATE NOT NULL,
  "LBM_HIEU_LUC_DEN" DATE,
  "LBM_TRANG_THAI" TEXT NOT NULL DEFAULT 'active',
  "LBM_GHI_CHU" TEXT,
  "LBM_TAO_LUC" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
  "LBM_TAO_BOI" TEXT,
  "LBM_CAP_NHAT_LUC" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
  "LBM_CAP_NHAT_BOI" TEXT,
  CONSTRAINT "LICH_BSK_MAU_pkey" PRIMARY KEY ("LBM_ID"),
  CONSTRAINT "ck_lbm_trang_thai" CHECK ("LBM_TRANG_THAI" IN ('active', 'inactive')),
  CONSTRAINT "ck_lbm_thu_trong_tuan" CHECK ("LBM_THU_TRONG_TUAN" BETWEEN 1 AND 6),
  CONSTRAINT "fk_lbm_bs" FOREIGN KEY ("BS_MA") REFERENCES "BAC_SI"("BS_MA") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_lbm_ck" FOREIGN KEY ("CK_MA") REFERENCES "CHUYEN_KHOA"("CK_MA") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_lbm_phong" FOREIGN KEY ("P_MA") REFERENCES "PHONG"("P_MA") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_lbm_buoi" FOREIGN KEY ("B_TEN") REFERENCES "BUOI"("B_TEN") ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE "DOT_LICH_TUAN" (
  "DLT_TUAN_BAT_DAU" DATE NOT NULL,
  "DLT_TUAN_KET_THUC" DATE NOT NULL,
  "DLT_TRANG_THAI" TEXT NOT NULL DEFAULT 'generated',
  "DLT_SINH_LUC" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
  "DLT_SINH_BOI" TEXT,
  "DLT_CHOT_LUC" TIMESTAMP(6),
  "DLT_CHOT_BOI" TEXT,
  "DLT_MO_SLOT_LUC" TIMESTAMP(6),
  "DLT_MO_SLOT_BOI" TEXT,
  "DLT_GHI_CHU" TEXT,
  CONSTRAINT "DOT_LICH_TUAN_pkey" PRIMARY KEY ("DLT_TUAN_BAT_DAU"),
  CONSTRAINT "ck_dlt_trang_thai" CHECK ("DLT_TRANG_THAI" IN ('generated', 'finalized', 'slot_opened'))
);

CREATE TABLE "YEU_CAU_LICH_BSK" (
  "YCL_ID" SERIAL NOT NULL,
  "BS_MA" INTEGER NOT NULL,
  "LBSK_N_NGAY" DATE NOT NULL,
  "LBSK_B_TEN" TEXT NOT NULL,
  "YCL_LOAI" TEXT NOT NULL,
  "YCL_LY_DO" TEXT NOT NULL,
  "YCL_TRANG_THAI" TEXT NOT NULL DEFAULT 'pending',
  "YCL_TRANG_THAI_TRUOC" TEXT,
  "YCL_NGAY_MOI" DATE,
  "YCL_BUOI_MOI" TEXT,
  "YCL_P_MA_MOI" INTEGER,
  "YCL_GOI_Y_BS_MA" INTEGER,
  "YCL_GHI_CHU_ADMIN" TEXT,
  "YCL_TAO_LUC" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
  "YCL_TAO_BOI" TEXT,
  "YCL_DUYET_LUC" TIMESTAMP(6),
  "YCL_DUYET_BOI" TEXT,
  CONSTRAINT "YEU_CAU_LICH_BSK_pkey" PRIMARY KEY ("YCL_ID"),
  CONSTRAINT "ck_ycl_loai" CHECK ("YCL_LOAI" IN ('leave', 'shift_change', 'room_change', 'other')),
  CONSTRAINT "ck_ycl_trang_thai" CHECK ("YCL_TRANG_THAI" IN ('pending', 'approved', 'rejected')),
  CONSTRAINT "fk_ycl_bs" FOREIGN KEY ("BS_MA") REFERENCES "BAC_SI"("BS_MA") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_ycl_lich" FOREIGN KEY ("BS_MA", "LBSK_N_NGAY", "LBSK_B_TEN") REFERENCES "LICH_BSK"("BS_MA", "N_NGAY", "B_TEN") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_ycl_phong_moi" FOREIGN KEY ("YCL_P_MA_MOI") REFERENCES "PHONG"("P_MA") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_ycl_bs_goi_y" FOREIGN KEY ("YCL_GOI_Y_BS_MA") REFERENCES "BAC_SI"("BS_MA") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_ycl_buoi_moi" FOREIGN KEY ("YCL_BUOI_MOI") REFERENCES "BUOI"("B_TEN") ON DELETE NO ACTION ON UPDATE NO ACTION
);

WITH existing_weeks AS (
  SELECT DISTINCT
    (
      "N_NGAY" - ((EXTRACT(ISODOW FROM "N_NGAY")::int - 1) * INTERVAL '1 day')
    )::date AS week_start
  FROM "LICH_BSK"
)
INSERT INTO "DOT_LICH_TUAN" (
  "DLT_TUAN_BAT_DAU",
  "DLT_TUAN_KET_THUC",
  "DLT_TRANG_THAI",
  "DLT_SINH_LUC",
  "DLT_CHOT_LUC",
  "DLT_CHOT_BOI",
  "DLT_MO_SLOT_LUC",
  "DLT_MO_SLOT_BOI"
)
SELECT
  weeks.week_start,
  (weeks.week_start + INTERVAL '5 day')::date,
  CASE
    WHEN slot_log."AL_CHANGED_AT" IS NOT NULL THEN 'slot_opened'
    WHEN finalized_log."AL_CHANGED_AT" IS NOT NULL THEN 'finalized'
    ELSE 'generated'
  END,
  CURRENT_TIMESTAMP,
  finalized_log."AL_CHANGED_AT",
  finalized_log."AL_CHANGED_BY",
  slot_log."AL_CHANGED_AT",
  slot_log."AL_CHANGED_BY"
FROM existing_weeks weeks
LEFT JOIN LATERAL (
  SELECT "AL_CHANGED_AT", "AL_CHANGED_BY"
  FROM "AUDIT_LOG"
  WHERE "AL_TABLE" = 'SCHEDULE_CYCLE'
    AND "AL_ACTION" = 'FINALIZED'
    AND "AL_PK" ->> 'weekStart' = to_char(weeks.week_start, 'YYYY-MM-DD')
  ORDER BY "AL_CHANGED_AT" DESC
  LIMIT 1
) finalized_log ON TRUE
LEFT JOIN LATERAL (
  SELECT "AL_CHANGED_AT", "AL_CHANGED_BY"
  FROM "AUDIT_LOG"
  WHERE "AL_TABLE" = 'SCHEDULE_CYCLE'
    AND "AL_ACTION" = 'SLOTS_GENERATED'
    AND "AL_PK" ->> 'weekStart' = to_char(weeks.week_start, 'YYYY-MM-DD')
  ORDER BY "AL_CHANGED_AT" DESC
  LIMIT 1
) slot_log ON TRUE;

WITH computed_rows AS (
  SELECT
    lb."BS_MA",
    lb."N_NGAY",
    lb."B_TEN",
    (
      lb."N_NGAY" - ((EXTRACT(ISODOW FROM lb."N_NGAY")::int - 1) * INTERVAL '1 day')
    )::date AS week_start
  FROM "LICH_BSK" lb
)
UPDATE "LICH_BSK" lb
SET
  "DLT_TUAN_BAT_DAU" = computed.week_start,
  "LBSK_NGUON" = CASE
    WHEN lb."LBSK_DUYET_BOI" = 'ADMIN_MANUAL' THEN 'admin_manual'
    ELSE 'legacy_registration'
  END,
  "LBSK_TRANG_THAI" = CASE
    WHEN lb."LBSK_TRANGTHAI_DUYET" = 'rejected' THEN 'cancelled'
    WHEN batch."DLT_TRANG_THAI" IN ('finalized', 'slot_opened')
      AND lb."LBSK_TRANGTHAI_DUYET" = 'approved' THEN 'finalized'
    WHEN lb."LBSK_TRANGTHAI_DUYET" = 'approved' THEN 'confirmed'
    ELSE 'generated'
  END,
  "LBSK_TAO_LUC" = COALESCE(lb."LBSK_DUYET_LUC", CURRENT_TIMESTAMP),
  "LBSK_CAP_NHAT_LUC" = COALESCE(lb."LBSK_DUYET_LUC", CURRENT_TIMESTAMP),
  "LBSK_XAC_NHAN_LUC" = CASE
    WHEN lb."LBSK_TRANGTHAI_DUYET" = 'approved' THEN COALESCE(lb."LBSK_DUYET_LUC", CURRENT_TIMESTAMP)
    ELSE NULL
  END
FROM computed_rows computed
JOIN "DOT_LICH_TUAN" batch
  ON batch."DLT_TUAN_BAT_DAU" = computed.week_start
WHERE lb."BS_MA" = computed."BS_MA"
  AND lb."N_NGAY" = computed."N_NGAY"
  AND lb."B_TEN" = computed."B_TEN";

ALTER TABLE "LICH_BSK"
ADD CONSTRAINT "ck_lich_bsk_nguon"
CHECK ("LBSK_NGUON" IN ('legacy_registration', 'template', 'admin_manual')),
ADD CONSTRAINT "ck_lich_bsk_trang_thai"
CHECK ("LBSK_TRANG_THAI" IN ('generated', 'confirmed', 'change_requested', 'adjusted', 'finalized', 'cancelled')),
ADD CONSTRAINT "fk_lich_bsk_mau"
FOREIGN KEY ("LBM_ID") REFERENCES "LICH_BSK_MAU"("LBM_ID") ON DELETE SET NULL ON UPDATE NO ACTION,
ADD CONSTRAINT "fk_lich_bsk_tuan"
FOREIGN KEY ("DLT_TUAN_BAT_DAU") REFERENCES "DOT_LICH_TUAN"("DLT_TUAN_BAT_DAU") ON DELETE SET NULL ON UPDATE NO ACTION;

CREATE INDEX "idx_lbm_bs" ON "LICH_BSK_MAU"("BS_MA");
CREATE INDEX "idx_lbm_ck" ON "LICH_BSK_MAU"("CK_MA");
CREATE INDEX "idx_lbm_phong" ON "LICH_BSK_MAU"("P_MA");
CREATE INDEX "idx_lbm_status_slot" ON "LICH_BSK_MAU"("LBM_TRANG_THAI", "LBM_THU_TRONG_TUAN", "B_TEN");
CREATE INDEX "idx_lbm_bs_slot" ON "LICH_BSK_MAU"("BS_MA", "LBM_THU_TRONG_TUAN", "B_TEN");
CREATE INDEX "idx_lbm_phong_slot" ON "LICH_BSK_MAU"("P_MA", "LBM_THU_TRONG_TUAN", "B_TEN");
CREATE INDEX "idx_lbm_hieu_luc" ON "LICH_BSK_MAU"("LBM_HIEU_LUC_TU", "LBM_HIEU_LUC_DEN");
CREATE INDEX "idx_dlt_trang_thai" ON "DOT_LICH_TUAN"("DLT_TRANG_THAI");
CREATE INDEX "idx_ycl_bs_trang_thai" ON "YEU_CAU_LICH_BSK"("BS_MA", "YCL_TRANG_THAI");
CREATE INDEX "idx_ycl_ngay" ON "YEU_CAU_LICH_BSK"("LBSK_N_NGAY");
CREATE INDEX "idx_ycl_tao_luc" ON "YEU_CAU_LICH_BSK"("YCL_TAO_LUC");
CREATE INDEX "idx_lich_bsk_mau" ON "LICH_BSK"("LBM_ID");
CREATE INDEX "idx_lich_bsk_tuan" ON "LICH_BSK"("DLT_TUAN_BAT_DAU");
CREATE INDEX "idx_lich_bsk_trang_thai" ON "LICH_BSK"("LBSK_TRANG_THAI");
