CREATE TABLE IF NOT EXISTS "PILOT_ROLLOUT_CONFIG" (
  "PRC_MA" SERIAL PRIMARY KEY,
  "PRC_COHORT_TYPE" TEXT,
  "PRC_COHORT_IDS" JSONB,
  "PRC_FEATURES" JSONB,
  "PRC_START_AT" TIMESTAMP(6),
  "PRC_END_AT" TIMESTAMP(6),
  "PRC_ENABLED" BOOLEAN NOT NULL DEFAULT FALSE,
  "PRC_NOTE" TEXT,
  "PRC_UPDATED_BY" TEXT,
  "PRC_UPDATED_AT" TIMESTAMP(6) NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_prc_enabled" ON "PILOT_ROLLOUT_CONFIG"("PRC_ENABLED");
CREATE INDEX IF NOT EXISTS "idx_prc_updated_at" ON "PILOT_ROLLOUT_CONFIG"("PRC_UPDATED_AT");
