BEGIN;

ALTER TABLE "DANG_KY"
  ADD COLUMN IF NOT EXISTS "DK_CO_BHYT" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "DK_LOAI_BHYT" TEXT,
  ADD COLUMN IF NOT EXISTS "DK_CO_BHTN" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "DK_BHTN_DON_VI" TEXT,
  ADD COLUMN IF NOT EXISTS "DK_PT_THANH_TOAN" TEXT;

ALTER TABLE "DANG_KY"
  ALTER COLUMN "DK_CO_BHYT" SET DEFAULT FALSE,
  ALTER COLUMN "DK_CO_BHTN" SET DEFAULT FALSE,
  ALTER COLUMN "DK_PT_THANH_TOAN" SET DEFAULT 'VNPAY';

UPDATE "DANG_KY"
SET
  "DK_CO_BHYT" = COALESCE("DK_CO_BHYT", FALSE),
  "DK_CO_BHTN" = COALESCE("DK_CO_BHTN", FALSE),
  "DK_PT_THANH_TOAN" = COALESCE(NULLIF("DK_PT_THANH_TOAN", ''), 'VNPAY')
WHERE
  "DK_CO_BHYT" IS NULL
  OR "DK_CO_BHTN" IS NULL
  OR "DK_PT_THANH_TOAN" IS NULL
  OR "DK_PT_THANH_TOAN" = '';

COMMIT;
