ALTER TABLE "DANG_KY"
  ADD COLUMN IF NOT EXISTS "DK_TRIEU_CHUNG" TEXT,
  ADD COLUMN IF NOT EXISTS "DK_GHI_CHU_TIEN_KHAM" TEXT,
  ADD COLUMN IF NOT EXISTS "DK_TIEN_KHAM_CAP_NHAT_LUC" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "DK_TIEN_KHAM_CAP_NHAT_BOI" TEXT;

CREATE TABLE IF NOT EXISTS "PRE_VISIT_ATTACHMENT" (
  "PVA_MA" SERIAL PRIMARY KEY,
  "DK_MA" INTEGER NOT NULL,
  "PVA_TEN_FILE" TEXT NOT NULL,
  "PVA_URL" TEXT,
  "PVA_LOAI_MIME" TEXT,
  "PVA_KICH_THUOC" INTEGER,
  "PVA_TAO_LUC" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "PVA_TAO_BOI" TEXT,
  "PVA_DA_XOA" BOOLEAN NOT NULL DEFAULT FALSE,
  "PVA_XOA_LUC" TIMESTAMP(6),
  "PVA_XOA_BOI" TEXT,
  CONSTRAINT "fk_pva_dk" FOREIGN KEY ("DK_MA") REFERENCES "DANG_KY"("DK_MA") ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "idx_pva_dk" ON "PRE_VISIT_ATTACHMENT"("DK_MA");
CREATE INDEX IF NOT EXISTS "idx_pva_dk_active" ON "PRE_VISIT_ATTACHMENT"("DK_MA", "PVA_DA_XOA");

CREATE TABLE IF NOT EXISTS "THONG_BAO_BATCH" (
  "TBB_MA" SERIAL PRIMARY KEY,
  "TBB_LOAI" TEXT NOT NULL,
  "TBB_TIEU_DE" TEXT,
  "TBB_NOI_DUNG" TEXT NOT NULL,
  "TBB_TIEU_CHI" JSONB,
  "TBB_IDEMPOTENCY_KEY" TEXT,
  "TBB_TONG_NGUOI_NHAN" INTEGER NOT NULL DEFAULT 0,
  "TBB_THANH_CONG" INTEGER NOT NULL DEFAULT 0,
  "TBB_THAT_BAI" INTEGER NOT NULL DEFAULT 0,
  "TBB_TRANG_THAI" TEXT NOT NULL DEFAULT 'COMPLETED',
  "TBB_METADATA" JSONB,
  "TBB_NGUOI_TAO" TEXT,
  "TBB_THOI_GIAN_TAO" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_tbb_loai" ON "THONG_BAO_BATCH"("TBB_LOAI");
CREATE INDEX IF NOT EXISTS "idx_tbb_nguoi_tao" ON "THONG_BAO_BATCH"("TBB_NGUOI_TAO");
CREATE INDEX IF NOT EXISTS "idx_tbb_tao_luc" ON "THONG_BAO_BATCH"("TBB_THOI_GIAN_TAO");
CREATE INDEX IF NOT EXISTS "idx_tbb_idempotency" ON "THONG_BAO_BATCH"("TBB_IDEMPOTENCY_KEY");

ALTER TABLE "THONG_BAO"
  ADD COLUMN IF NOT EXISTS "TB_BATCH_MA" INTEGER;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_tb_batch'
  ) THEN
    ALTER TABLE "THONG_BAO"
      ADD CONSTRAINT "fk_tb_batch"
      FOREIGN KEY ("TB_BATCH_MA")
      REFERENCES "THONG_BAO_BATCH"("TBB_MA")
      ON DELETE SET NULL
      ON UPDATE NO ACTION;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_tb_batch" ON "THONG_BAO"("TB_BATCH_MA");
CREATE INDEX IF NOT EXISTS "idx_dk_bs_ngay_trangthai" ON "DANG_KY"("BS_MA", "N_NGAY", "DK_TRANG_THAI");
