ALTER TABLE "LICH_BSK"
ADD COLUMN "LBSK_TRANGTHAI_DUYET" TEXT NOT NULL DEFAULT 'pending',
ADD COLUMN "LBSK_DUYET_BOI" TEXT,
ADD COLUMN "LBSK_DUYET_LUC" TIMESTAMP(6);

UPDATE "LICH_BSK"
SET "LBSK_TRANGTHAI_DUYET" = CASE
  WHEN "LBSK_GHI_CHU" LIKE '[#SCHEDULE_STATUS:rejected]%' THEN 'rejected'
  WHEN "LBSK_GHI_CHU" LIKE '[#SCHEDULE_STATUS:pending]%' THEN 'pending'
  WHEN "LBSK_GHI_CHU" LIKE '[#SCHEDULE_STATUS:approved]%' THEN 'approved'
  WHEN "LBSK_GHI_CHU" LIKE '[#SCHEDULE_STATUS:official]%' THEN 'approved'
  ELSE 'approved'
END;

ALTER TABLE "LICH_BSK"
ADD CONSTRAINT "ck_lich_bsk_trangthai_duyet"
CHECK ("LBSK_TRANGTHAI_DUYET" IN ('pending', 'approved', 'rejected'));
