ALTER TABLE "PRE_VISIT_ATTACHMENT"
  ADD COLUMN IF NOT EXISTS "PVA_STORAGE_KEY" TEXT,
  ADD COLUMN IF NOT EXISTS "PVA_EXT" TEXT,
  ADD COLUMN IF NOT EXISTS "PVA_SCAN_STATUS" TEXT NOT NULL DEFAULT 'SCAN_REQUESTED',
  ADD COLUMN IF NOT EXISTS "PVA_SCAN_LUC" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "PVA_REVOKED_AT" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "PVA_REVOKED_BY" TEXT,
  ADD COLUMN IF NOT EXISTS "PVA_REVOKE_REASON" TEXT;

CREATE INDEX IF NOT EXISTS "idx_pva_scan_status" ON "PRE_VISIT_ATTACHMENT"("PVA_SCAN_STATUS");

ALTER TABLE "THONG_BAO_BATCH"
  ADD COLUMN IF NOT EXISTS "TBB_DA_XU_LY" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "TBB_BAT_DAU_LUC" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "TBB_HOAN_TAT_LUC" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "TBB_BATCH_CHA_MA" INTEGER,
  ADD COLUMN IF NOT EXISTS "TBB_LOI_GAN_NHAT" TEXT,
  ALTER COLUMN "TBB_TRANG_THAI" SET DEFAULT 'QUEUED';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_tbb_parent'
  ) THEN
    ALTER TABLE "THONG_BAO_BATCH"
      ADD CONSTRAINT "fk_tbb_parent"
      FOREIGN KEY ("TBB_BATCH_CHA_MA")
      REFERENCES "THONG_BAO_BATCH"("TBB_MA")
      ON DELETE SET NULL
      ON UPDATE NO ACTION;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_tbb_status" ON "THONG_BAO_BATCH"("TBB_TRANG_THAI");

CREATE TABLE IF NOT EXISTS "THONG_BAO_BATCH_RECIPIENT" (
  "TBR_MA" SERIAL PRIMARY KEY,
  "TBB_MA" INTEGER NOT NULL,
  "TK_SDT" TEXT NOT NULL,
  "DK_MA" INTEGER,
  "TBR_TRANG_THAI" TEXT NOT NULL DEFAULT 'QUEUED',
  "TBR_SO_LAN_THU" INTEGER NOT NULL DEFAULT 0,
  "TBR_LOI" TEXT,
  "TBR_LAST_SENT_AT" TIMESTAMP(6),
  "TBR_CREATED_AT" TIMESTAMP(6) NOT NULL DEFAULT NOW(),
  "TBR_UPDATED_AT" TIMESTAMP(6) NOT NULL DEFAULT NOW(),
  CONSTRAINT "fk_tbr_batch" FOREIGN KEY ("TBB_MA") REFERENCES "THONG_BAO_BATCH"("TBB_MA") ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "idx_tbr_batch" ON "THONG_BAO_BATCH_RECIPIENT"("TBB_MA");
CREATE INDEX IF NOT EXISTS "idx_tbr_batch_status" ON "THONG_BAO_BATCH_RECIPIENT"("TBB_MA", "TBR_TRANG_THAI");
CREATE INDEX IF NOT EXISTS "idx_tbr_phone" ON "THONG_BAO_BATCH_RECIPIENT"("TK_SDT");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_tbr_batch_recipient" ON "THONG_BAO_BATCH_RECIPIENT"("TBB_MA", "TK_SDT", "DK_MA");

ALTER TABLE "WAITLIST_ENTRY"
  ADD COLUMN IF NOT EXISTS "WL_HOLD_TOKEN" TEXT,
  ADD COLUMN IF NOT EXISTS "WL_HOLD_EXPIRES_AT" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "WL_PROMOTED_DK_MA" INTEGER,
  ADD COLUMN IF NOT EXISTS "WL_SKIP_REASON" TEXT,
  ADD COLUMN IF NOT EXISTS "WL_SOURCE_EVENT" TEXT;

DROP INDEX IF EXISTS "uq_waitlist_active_patient_slot";
CREATE UNIQUE INDEX IF NOT EXISTS "uq_waitlist_active_patient_slot"
ON "WAITLIST_ENTRY" ("BN_MA", "BS_MA", "N_NGAY", "B_TEN", "KG_MA")
WHERE "WL_STATUS" IN ('WAITING', 'NOTIFIED', 'HOLDING');

CREATE INDEX IF NOT EXISTS "idx_waitlist_hold_expiry" ON "WAITLIST_ENTRY"("WL_HOLD_EXPIRES_AT");

CREATE TABLE IF NOT EXISTS "PAYMENT_WEBHOOK_EVENT" (
  "PWE_MA" SERIAL PRIMARY KEY,
  "PWE_PROVIDER" TEXT NOT NULL,
  "PWE_EVENT_KEY" TEXT NOT NULL UNIQUE,
  "PWE_EVENT_TYPE" TEXT,
  "PWE_REF" TEXT,
  "PWE_SIGNATURE_OK" BOOLEAN NOT NULL DEFAULT FALSE,
  "PWE_TRANG_THAI" TEXT NOT NULL DEFAULT 'RECEIVED',
  "PWE_PAYLOAD" JSONB,
  "PWE_LOI" TEXT,
  "PWE_CREATED_AT" TIMESTAMP(6) NOT NULL DEFAULT NOW(),
  "PWE_PROCESSED_AT" TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS "idx_pwe_provider_time" ON "PAYMENT_WEBHOOK_EVENT"("PWE_PROVIDER", "PWE_CREATED_AT");
CREATE INDEX IF NOT EXISTS "idx_pwe_status" ON "PAYMENT_WEBHOOK_EVENT"("PWE_TRANG_THAI");

CREATE TABLE IF NOT EXISTS "PAYMENT_RECONCILIATION_JOB" (
  "PRJ_MA" SERIAL PRIMARY KEY,
  "PRJ_NGAY" DATE NOT NULL,
  "PRJ_TRANG_THAI" TEXT NOT NULL DEFAULT 'COMPLETED',
  "PRJ_TONG_KIEM_TRA" INTEGER NOT NULL DEFAULT 0,
  "PRJ_SO_MISMATCH" INTEGER NOT NULL DEFAULT 0,
  "PRJ_GHI_CHU" TEXT,
  "PRJ_TAO_LUC" TIMESTAMP(6) NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_prj_date" ON "PAYMENT_RECONCILIATION_JOB"("PRJ_NGAY");

CREATE TABLE IF NOT EXISTS "PAYMENT_RECONCILIATION_ISSUE" (
  "PRI_MA" SERIAL PRIMARY KEY,
  "PRJ_MA" INTEGER NOT NULL,
  "TT_MA" INTEGER,
  "DK_MA" INTEGER,
  "PRI_LOAI" TEXT NOT NULL,
  "PRI_MO_TA" TEXT NOT NULL,
  "PRI_TRANG_THAI" TEXT NOT NULL DEFAULT 'OPEN',
  "PRI_METADATA" JSONB,
  "PRI_TAO_LUC" TIMESTAMP(6) NOT NULL DEFAULT NOW(),
  CONSTRAINT "fk_pri_prj" FOREIGN KEY ("PRJ_MA") REFERENCES "PAYMENT_RECONCILIATION_JOB"("PRJ_MA") ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS "idx_pri_job" ON "PAYMENT_RECONCILIATION_ISSUE"("PRJ_MA");
CREATE INDEX IF NOT EXISTS "idx_pri_status" ON "PAYMENT_RECONCILIATION_ISSUE"("PRI_TRANG_THAI");
