ALTER TABLE "DANG_KY"
  ADD COLUMN IF NOT EXISTS "DK_CO_BHYT" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "DK_LOAI_BHYT" TEXT,
  ADD COLUMN IF NOT EXISTS "DK_CO_BHTN" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "DK_BHTN_DON_VI" TEXT,
  ADD COLUMN IF NOT EXISTS "DK_PT_THANH_TOAN" TEXT;
