ALTER TABLE "BENH_NHAN"
ADD COLUMN "BN_NGAY_SINH" DATE,
ADD COLUMN "BN_SO_BHYT" TEXT,
ADD COLUMN "BN_DIA_CHI" TEXT,
ADD COLUMN "BN_QUAN_HE_VOI_TK" TEXT,
ADD COLUMN "BN_DA_VO_HIEU" BOOLEAN NOT NULL DEFAULT false;
