CREATE TABLE IF NOT EXISTS "WAITLIST_ENTRY" (
  "WL_ID" SERIAL PRIMARY KEY,
  "BN_MA" INTEGER NOT NULL,
  "BS_MA" INTEGER NOT NULL,
  "N_NGAY" DATE NOT NULL,
  "B_TEN" TEXT NOT NULL,
  "KG_MA" INTEGER NOT NULL,
  "WL_STATUS" TEXT NOT NULL DEFAULT 'WAITING',
  "WL_PRIORITY" INTEGER NOT NULL DEFAULT 0,
  "WL_NOTE" TEXT,
  "WL_SOURCE" TEXT,
  "WL_CREATED_AT" TIMESTAMP(6) NOT NULL DEFAULT NOW(),
  "WL_UPDATED_AT" TIMESTAMP(6) NOT NULL DEFAULT NOW(),
  "WL_NOTIFIED_AT" TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS "idx_waitlist_patient" ON "WAITLIST_ENTRY" ("BN_MA");
CREATE INDEX IF NOT EXISTS "idx_waitlist_slot" ON "WAITLIST_ENTRY" ("BS_MA", "N_NGAY", "B_TEN", "KG_MA");
CREATE INDEX IF NOT EXISTS "idx_waitlist_status" ON "WAITLIST_ENTRY" ("WL_STATUS");

CREATE UNIQUE INDEX IF NOT EXISTS "uq_waitlist_active_patient_slot"
ON "WAITLIST_ENTRY" ("BN_MA", "BS_MA", "N_NGAY", "B_TEN", "KG_MA")
WHERE "WL_STATUS" IN ('WAITING', 'NOTIFIED');
